update

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -49,7 +49,11 @@ jobs:
           WORKDIR: /root/guimar_app
         run: |
           ssh $USERNAME@$HOST '
-            cd $WORKDIR &&
+            cd $WORKDIR || exit 1
+            if [ ! -d ".git" ]; then
+              echo "Error: No es un repositorio Git. Verifica la ruta y el contenido."
+              exit 1
+            fi
             git pull origin master &&
             docker-compose down &&
             docker-compose up --build -d
